ALTER TABLE public.company_settings
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'السودان',
  ADD COLUMN IF NOT EXISTS postbox text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS invoice_prefix text DEFAULT 'INV-',
  ADD COLUMN IF NOT EXISTS quote_prefix text DEFAULT 'QT-',
  ADD COLUMN IF NOT EXISTS purchase_prefix text DEFAULT 'PO-',
  ADD COLUMN IF NOT EXISTS recurring_prefix text DEFAULT 'REC-',
  ADD COLUMN IF NOT EXISTS return_prefix text DEFAULT 'RET-',
  ADD COLUMN IF NOT EXISTS transaction_prefix text DEFAULT 'TRX-',
  ADD COLUMN IF NOT EXISTS invoice_notes text DEFAULT 'شكراً لتعاملكم معنا',
  ADD COLUMN IF NOT EXISTS invoice_footer text,
  ADD COLUMN IF NOT EXISTS payment_terms_days integer DEFAULT 30,
  ADD COLUMN IF NOT EXISTS show_tax boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_discount boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_shipping boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_account text,
  ADD COLUMN IF NOT EXISTS iban text;